### ISSUE TITLE
a broken link on the website

### ISSUE THREAD

**Issue by husisy** [GiggleLiu/ScientificComputingDemos#8]
![image](https://github.com/GiggleLiu/ScientificComputingDemos/assets/17511292/3cb7005c-3e0d-4f45-8bd7-f66307d2855c)

hyperlink highlighted in the screenshot is broken

**Comment by GiggleLiu** [comment]
Yeah, I haven’t made the repo public. Will do it after cleaning up the repo.

**Comment by GiggleLiu** [comment]
Closing the issue for the book repo has been open sourced: https://github.com/GiggleLiu/ScientificComputingForPhysicists
